
- name: playbook para vagrant 
  hosts: all 
  become: yes 
  tasks: 
    - name: install epel-release
      package: 
       name: 
         - epel-release
         - vim 
       state: present 


    - name: bloco do etc hosts 
      blockinfile: 
        path: /etc/hosts
        block: | 
               192.168.33.151 node1.olivarius.com.br
               192.168.33.152 node2.olivarius.com.br
               192.168.33.153 node3.olivarius.com.br
    - name: execute yum update 
      shell: yum update -y 


    - name: install repo kubernetes 
      blockinfile:
              path: /etc/yum.repos.d/kubernetes.repo
              create: yes 
              block: | 
                      [kubernetes]
                      name=Kubernetes
                      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
                      enabled=1
                      gpgcheck=1
                      repo_gpgcheck=1
                      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                      exclude=kube*
    
    - name: disable selinux
      selinux: 
        state: disabled 

    - name: mandando o setenforce 
      shell: setenforce 0 

    
    - name: install pacotes do kubernetes 
      yum:
       name: 
        - kubelet 
        - kubeadm
        - kubectl 
       disable_excludes: kubernetes



    - name: enable service kubelect 
      service: 
        name: kubelet
        state: started
        enabled: yes 

    - name: disable swap memory 
      shell: swapoff -a 


    - name: criar bloco da parte de rede do kubernetes 
      blockinfile: 
       path: /etc/sysctl.d/k8s.conf
       create: yes 
       block: | 
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
         

    - name: habilitar a parte de rede
      shell: sysctl --system 


    - name: bora atualizar o yum dnv 
      shell: yum update -y 

    - name: install docker 
      shell: curl -fsSL https://get.docker.com | bash 

    - name: start docker 
      service: 
        name: docker 
        state: started
        enabled: yes 

